// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqUiQ8wGc23TYtPZ98knKzSPbEUb0YtUg',
    appId: '1:1094598187571:web:a8abb6189a7d760efba146',
    messagingSenderId: '1094598187571',
    projectId: 'fir-auth-flutter-527a9',
    authDomain: 'fir-auth-flutter-527a9.firebaseapp.com',
    storageBucket: 'fir-auth-flutter-527a9.appspot.com',
    measurementId: 'G-WVFSKQHX7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4C3MEixnCwxT4hmCOf6XEU9lmQIESQyc',
    appId: '1:1094598187571:android:6dbe9d9490265b0afba146',
    messagingSenderId: '1094598187571',
    projectId: 'fir-auth-flutter-527a9',
    storageBucket: 'fir-auth-flutter-527a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBert90bj-_xMuO5sxjnKasUuQ6qlC8v0Q',
    appId: '1:1094598187571:ios:52fcbf089e1167b4fba146',
    messagingSenderId: '1094598187571',
    projectId: 'fir-auth-flutter-527a9',
    storageBucket: 'fir-auth-flutter-527a9.appspot.com',
    iosBundleId: 'com.kazungudev.firebaseAuthFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBert90bj-_xMuO5sxjnKasUuQ6qlC8v0Q',
    appId: '1:1094598187571:ios:39570655ba64d398fba146',
    messagingSenderId: '1094598187571',
    projectId: 'fir-auth-flutter-527a9',
    storageBucket: 'fir-auth-flutter-527a9.appspot.com',
    iosBundleId: 'com.kazungudev.firebaseAuthFlutter.RunnerTests',
  );
}
